[bundle]
output = "zig-plugins.so"

[[plugins]]
source = "./file-logger"

[[plugins]]
source = "./access-control"

[[plugins]]
source = "./byte-counter"

[[plugins]]
source = "./content-filter"

[[plugins]]
source = "./text-transform"

[[plugins]]
source = "./net-logger"

[[plugins]]
source = "./net-transform"

[[plugins]]
source = "./http-access-logs"

[[plugins]]
source = "./http-structured-logger"

[[plugins]]
source = "./http-rewrite"

[[plugins]]
source = "./http-access-logs"
